### ISSUE TITLE
Build Docker container & docker-compose files

### ISSUE THREAD

**Issue by kevinbowen777** [kevinbowen777/django_start#2]
This will the standardized Dhckerfile going forward, for now.
```
# Pull base image
FROM python:3.10

ARG DJANGO_START

# Set environment variables
ENV DJANGO_POLLS=${DJANGO_START} \
  PYTHONDONTWRITEBYTECODE=1 \
  PYTHONFAULTHANDLER=1 \
  PYTHONUNBUFFERED=1 \
  PYTHONHASHSEED=random \
  PIP_NO_CACHE_DIR=off \
  PIP_DISABLE_PIP_VERSION_CHECK=on \
  PIP_DEFAULT_TIMEOUT=100 \
  POETRY_VERSION=1.1.13

# System dependencies
RUN pip install "poetry==$POETRY_VERSION"

# Set work directory
WORKDIR /django_polls

# Install dependencies
COPY poetry.lock pyproject.toml /django_start/

# Project initialization:
RUN poetry config virtualenvs.create false
RUN poetry install

# Copy project
COPY . /django_start/
```
### docker-compose.yml file
```
version: "3.7"

services:
  web:
    build: .
    command: python /django_polls/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/django_polls
    ports:
      - 8000:8000
```
References:
 - https://stackoverflow.com/a/54763270/1704582
 - https://github.com/wemake-services/wemake-django-template/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/docker/django/Dockerfile
